name: Attach Artifacts Test

on:
  push:
    branches:
      - attach-artifacts-test
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: spring-io/spring-security-release-tools/.github/workflows/build.yml@v1
  attach-artifacts:
    name: Attach Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: spring-io/spring-gradle-build-action@v2
      - run: ./gradlew publishMavenJavaPublicationToLocalRepository
      - run: pushd build && zip -r artifacts publications && popd
      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/artifacts.zip
